### ISSUE TITLE
#lobbies: tagged discord id sometimes invalid

### ISSUE THREAD

**Issue by kiwec** [kiwec/osu-ranked-lobbies#1]
![2021-12-06-193714_368x445_scrot](https://user-images.githubusercontent.com/1957540/144902757-f80312c1-bce5-4eb3-8467-788069812fbd.png)

**Comment by kiwec** [comment]
Not fixed - the tagged ID is never used, unless it's the bot, yourself, or a user you mentioned while discord was open.

Copy/pasting the user mention "fixes" it, but just for you, until you refresh. Weird.

**Comment by coozieki** [comment]
I did some investigations and i don't think this problem is fixable. Discord client doesn't match ids and usernames unless 1) the person is in your friend list 2) you have seen the persons message or mention in one of the channels 3) you have found him in server's member list and then it is cached until you restart app. There is no other way to make it match id and username as far as i understand.
https://www.reddit.com/r/discordapp/comments/lsuf4z/user_id_bug_how_to_fix_discord_not_showing_the/

Alternatively you could just print username and discriminator without mentioning. I don't see any other way

**Comment by kiwec** [comment]
Now linking to the user's profile page instead.
